#######################################################
# 
# A.py
# Python implementation of the Class A
# Generated by Enterprise Architect
# Created on:      08-5��-2021 15:22:03
# Original author: 70748
# 
#######################################################


class A:
    def showMe(self):
        print("A's showMe is called")