#######################################################
# 
# B.py
# Python implementation of the Class B
# Generated by Enterprise Architect
# Created on:      08-5��-2021 15:22:03
# Original author: 70748
# 
#######################################################
from pkg.A import A

class B(A):
    def showMe(self):
        super().showMe()
        print("B's showMe is called")