#######################################################
# 
# C.py
# Python implementation of the Class C
# Generated by Enterprise Architect
# Created on:      08-5��-2021 15:22:03
# Original author: 70748
# 
#######################################################
from pkg.A import A

class C(A):
    def showMe(self):
        super().showMe()
        print("C's showMe is called")