#######################################################
# 
# D.py
# Python implementation of the Class D
# Generated by Enterprise Architect
# Created on:      08-5��-2021 15:22:03
# Original author: 70748
# 
#######################################################
from pkg.B import B
from pkg.C import C
from pkg.A import A

class D(C,B):
    def showMe(self):
        A.showMe(self)
        # super().showMe()
        print("D's showMe is called")