#######################################################
#
# Cart.py
# Python implementation of the Class Cart
# Generated by Enterprise Architect
# Created on:      20-4��-2021 13:21:57
# Original author: 70748
#
#######################################################
from .Item import Item


class Cart:
    def __init__(self, items: list):
        self.items = items

    def total(self):
        if len(self.items)>0:
            return sum(item.total() for item in self.items)
        else:
            return 0
            
