#######################################################
#
# FidelityPromo.py
# Python implementation of the Class FidelityPromo
# Generated by Enterprise Architect
# Created on:      20-4��-2021 13:21:58
# Original author: 70748
#
#######################################################
from .Order import Order
from .Promotion import Promotion


class FidelityPromo(Promotion):
    def discount(self, order: Order):
        if order.customer.fidelity>=1000:
            return 0.05*order.total()
        else:
            return 0
