#######################################################
#
# LargeOrderPromo.py
# Python implementation of the Class LargeOrderPromo
# Generated by Enterprise Architect
# Created on:      20-4��-2021 13:21:58
# Original author: 70748
#
#######################################################
from .Order import Order
from .Promotion import Promotion


class LargeOrderPromo(Promotion):
    # 不同商品10个以上时，0.7折
    def discount(self, order: Order):
        if len(order.cart.items) >= 10:
            return order.total()*0.07
        else:
            return 0
