#######################################################
#
# BulkitemPromo.py
# Python implementation of the Class BulkitemPromo
# Generated by Enterprise Architect
# Created on:      20-4��-2021 13:21:57
# Original author: 70748
#
#######################################################
from .Order import Order
from .Promotion import Promotion


class BulkitemPromo(Promotion):
    def discount(self, order: Order):
        discount = 0
        for item in order.cart.items:
            if item.num > 20:
                discount += item.total()*0.1
        return discount
