#######################################################
#
# Customer.py
# Python implementation of the Class Customer
# Generated by Enterprise Architect
# Created on:      20-4��-2021 13:21:58
# Original author: 70748
#
#######################################################
# from .Order import Order


class Customer:

    def __init__(self, name: str, fidelity: int) -> None:
        self.fidelity = fidelity
        self.name = name
