#######################################################
#
# Promotion.py
# Python implementation of the Class Promotion
# Generated by Enterprise Architect
# Created on:      20-4��-2021 13:21:58
# Original author: 70748
#
#######################################################
from abc import ABC, abstractmethod
# from .Order import Order


class Promotion(ABC):
    @abstractmethod
    def discount(self, order: "Order"):
        pass
