#######################################################
#
# Item.py
# Python implementation of the Class Item
# Generated by Enterprise Architect
# Created on:      20-4��-2021 13:21:58
# Original author: 70748
#
#######################################################


class Item:
    def __init__(self, name: str, num: int, price: float) -> None:
        self.name = name
        self.num = num
        self.price = price

    def total(self):
        return self.num*self.price
